export const initialIngredients = [
  {
    name: 'Mouka hladká',
    qty: 70,
    min_qty: 25,
    price: 16,
  },
  {
    name: 'Cukr',
    qty: 65,
    min_qty: 20,
    price: 4,
  },
  {
    name: 'Máslo',
    qty: 34,
    min_qty: 12,
    price: 24,
  },
  {
    name: 'Vejce',
    qty: 52,
    min_qty: 18,
    price: 8,
  },
  {
    name: 'Mléko',
    qty: 48,
    min_qty: 16,
    price: 12,
  },
  {
    name: 'Smetana',
    qty: 26,
    min_qty: 10,
    price: 18,
  },
  {
    name: 'Kakao',
    qty: 18,
    min_qty: 6,
    price: 15,
  },
  {
    name: 'Vanilka',
    qty: 14,
    min_qty: 5,
    price: 21,
  },
  {
    name: 'Jahody',
    qty: 22,
    min_qty: 8,
    price: 19,
  },
  {
    name: 'Želatina',
    qty: 15,
    min_qty: 6,
    price: 13,
  },
]

export const initialProducts = [
  {
    id: 1,
    name: 'Dortík Pavlova',
    ingredients: [
      { name: 'Vejce', qty: 3 },
      { name: 'Cukr', qty: 3 },
      { name: 'Smetana', qty: 2 },
      { name: 'Jahody', qty: 2 },
    ],
    price: 76,
    status: 'enabledProduct',
  },
  {
    id: 2,
    name: 'Jahodový cheesecake',
    ingredients: [
      { name: 'Smetana', qty: 3 },
      { name: 'Cukr', qty: 2 },
      { name: 'Želatina', qty: 1 },
      { name: 'Jahody', qty: 3 },
    ],
    price: 84,
    status: 'enabledProduct',
  },
  {
    id: 3,
    name: 'Čokoládový větrník',
    ingredients: [
      { name: 'Mouka hladká', qty: 3 },
      { name: 'Vejce', qty: 2 },
      { name: 'Máslo', qty: 2 },
      { name: 'Kakao', qty: 1 },
      { name: 'Smetana', qty: 2 },
    ],
    price: 58,
    status: 'enabledProduct',
  },
  {
    id: 4,
    name: 'Vanilkový éclair',
    ingredients: [
      { name: 'Mouka hladká', qty: 2 },
      { name: 'Vejce', qty: 2 },
      { name: 'Máslo', qty: 1 },
      { name: 'Vanilka', qty: 1 },
      { name: 'Mléko', qty: 2 },
    ],
    price: 52,
    status: 'enabledProduct',
  },
  {
    id: 5,
    name: 'Malinový tart',
    ingredients: [
      { name: 'Mouka hladká', qty: 2 },
      { name: 'Máslo', qty: 2 },
      { name: 'Cukr', qty: 2 },
      { name: 'Smetana', qty: 2 },
      { name: 'Jahody', qty: 2 },
    ],
    price: 68,
    status: 'enabledProduct',
  },
  {
    id: 6,
    name: 'Míša řez',
    ingredients: [
      { name: 'Mouka hladká', qty: 2 },
      { name: 'Cukr', qty: 2 },
      { name: 'Vejce', qty: 2 },
      { name: 'Smetana', qty: 2 },
      { name: 'Kakao', qty: 1 },
    ],
    price: 62,
    status: 'enabledProduct',
  },
  {
    id: 7,
    name: 'Borůvkový koláč',
    ingredients: [
      { name: 'Mouka hladká', qty: 3 },
      { name: 'Máslo', qty: 2 },
      { name: 'Cukr', qty: 2 },
      { name: 'Vejce', qty: 1 },
      { name: 'Želatina', qty: 1 },
    ],
    price: 64,
    status: 'enabledProduct',
  },
  {
    id: 8,
    name: 'Makronky',
    ingredients: [
      { name: 'Vejce', qty: 3 },
      { name: 'Cukr', qty: 3 },
      { name: 'Vanilka', qty: 1 },
      { name: 'Smetana', qty: 1 },
    ],
    price: 46,
    status: 'enabledProduct',
  },
  {
    id: 9,
    name: 'Linecký řez',
    ingredients: [
      { name: 'Mouka hladká', qty: 3 },
      { name: 'Máslo', qty: 2 },
      { name: 'Cukr', qty: 2 },
      { name: 'Jahody', qty: 2 },
    ],
    price: 54,
    status: 'enabledProduct',
  },
  {
    id: 10,
    name: 'Tvarohový dort',
    ingredients: [
      { name: 'Smetana', qty: 3 },
      { name: 'Mléko', qty: 2 },
      { name: 'Cukr', qty: 2 },
      { name: 'Želatina', qty: 1 },
      { name: 'Vanilka', qty: 1 },
    ],
    price: 82,
    status: 'enabledProduct',
  },
]

export const initialOrders = [
  { id: 1, products: [{ name: 'Dortík Pavlova', quantity: 1, unitPrice: 76 }], quantity: 1, totalPrice: 76, isEnabled: true, timestamp: '2025-01-07T09:00:00.000Z' },
  { id: 2, products: [{ name: 'Jahodový cheesecake', quantity: 1, unitPrice: 84 }], quantity: 1, totalPrice: 84, isEnabled: true, timestamp: '2025-02-09T09:20:00.000Z' },
  { id: 3, products: [{ name: 'Čokoládový větrník', quantity: 2, unitPrice: 58 }], quantity: 2, totalPrice: 116, isEnabled: true, timestamp: '2025-03-11T09:40:00.000Z' },
  { id: 4, products: [{ name: 'Vanilkový éclair', quantity: 2, unitPrice: 52 }], quantity: 2, totalPrice: 104, isEnabled: true, timestamp: '2025-04-13T10:00:00.000Z' },
  { id: 5, products: [{ name: 'Malinový tart', quantity: 1, unitPrice: 68 }], quantity: 1, totalPrice: 68, isEnabled: true, timestamp: '2025-05-15T10:20:00.000Z' },
  { id: 6, products: [{ name: 'Míša řez', quantity: 2, unitPrice: 62 }], quantity: 2, totalPrice: 124, isEnabled: true, timestamp: '2025-06-17T10:40:00.000Z' },
  { id: 7, products: [{ name: 'Borůvkový koláč', quantity: 1, unitPrice: 64 }], quantity: 1, totalPrice: 64, isEnabled: true, timestamp: '2025-07-19T11:00:00.000Z' },
  { id: 8, products: [{ name: 'Makronky', quantity: 3, unitPrice: 46 }], quantity: 3, totalPrice: 138, isEnabled: true, timestamp: '2025-08-21T11:20:00.000Z' },
  { id: 9, products: [{ name: 'Linecký řez', quantity: 2, unitPrice: 54 }], quantity: 2, totalPrice: 108, isEnabled: true, timestamp: '2025-09-23T11:40:00.000Z' },
  { id: 10, products: [{ name: 'Tvarohový dort', quantity: 1, unitPrice: 82 }], quantity: 1, totalPrice: 82, isEnabled: true, timestamp: '2025-10-25T12:00:00.000Z' },
  { id: 11, products: [{ name: 'Dortík Pavlova', quantity: 1, unitPrice: 76 }, { name: 'Makronky', quantity: 1, unitPrice: 46 }], quantity: 2, totalPrice: 170, isEnabled: true, timestamp: '2025-11-17T12:20:00.000Z' },
  { id: 12, products: [{ name: 'Jahodový cheesecake', quantity: 2, unitPrice: 84 }], quantity: 2, totalPrice: 168, isEnabled: true, timestamp: '2025-12-19T12:40:00.000Z' },
  { id: 13, products: [{ name: 'Čokoládový větrník', quantity: 2, unitPrice: 58 }], quantity: 2, totalPrice: 116, isEnabled: true, timestamp: '2026-01-08T09:10:00.000Z' },
  { id: 14, products: [{ name: 'Vanilkový éclair', quantity: 1, unitPrice: 52 }], quantity: 1, totalPrice: 52, isEnabled: true, timestamp: '2026-02-10T09:30:00.000Z' },
  { id: 15, products: [{ name: 'Malinový tart', quantity: 2, unitPrice: 68 }], quantity: 2, totalPrice: 136, isEnabled: true, timestamp: '2026-03-12T09:50:00.000Z' },
  { id: 16, products: [{ name: 'Tvarohový dort', quantity: 1, unitPrice: 82 }], quantity: 1, totalPrice: 82, isEnabled: true, timestamp: '2026-04-14T10:10:00.000Z' },
  // { id: 17, products: [{ name: 'Borůvkový koláč', quantity: 2, unitPrice: 64 }], quantity: 2, totalPrice: 128, isEnabled: true, timestamp: '2026-05-16T10:30:00.000Z' },
  // { id: 18, products: [{ name: 'Míša řez', quantity: 2, unitPrice: 62 }], quantity: 2, totalPrice: 124, isEnabled: true, timestamp: '2026-06-18T10:50:00.000Z' },
  // { id: 19, products: [{ name: 'Linecký řez', quantity: 3, unitPrice: 54 }], quantity: 3, totalPrice: 162, isEnabled: true, timestamp: '2026-07-20T11:10:00.000Z' },
  // { id: 20, products: [{ name: 'Makronky', quantity: 4, unitPrice: 46 }], quantity: 4, totalPrice: 184, isEnabled: true, timestamp: '2026-08-22T11:30:00.000Z' },
  // { id: 21, products: [{ name: 'Dortík Pavlova', quantity: 1, unitPrice: 76 }, { name: 'Tvarohový dort', quantity: 1, unitPrice: 82 }], quantity: 2, totalPrice: 316, isEnabled: true, timestamp: '2026-09-24T11:50:00.000Z' },
  // { id: 22, products: [{ name: 'Jahodový cheesecake', quantity: 1, unitPrice: 84 }, { name: 'Malinový tart', quantity: 1, unitPrice: 68 }], quantity: 2, totalPrice: 304, isEnabled: true, timestamp: '2026-10-26T12:10:00.000Z' },
  // { id: 23, products: [{ name: 'Borůvkový koláč', quantity: 2, unitPrice: 64 }], quantity: 2, totalPrice: 128, isEnabled: true, timestamp: '2026-11-18T12:30:00.000Z' },
  // { id: 24, products: [{ name: 'Čokoládový větrník', quantity: 2, unitPrice: 58 }, { name: 'Vanilkový éclair', quantity: 1, unitPrice: 52 }], quantity: 3, totalPrice: 220, isEnabled: true, timestamp: '2026-12-20T12:50:00.000Z' },
]

export const appInfo = {
  storeName: 'Cukrárna U Sladké tečky',
  address: 'Jateční 22, Plzeň',
}
